#pragma once

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 832
#define MAP_WIDTH 16
#define MAP_HEIGHT 13
#define GRAVITY_STRENGTH 9.81f
#define INITIAL_JUMP_FORCE 40.0f
#define JUMP_FORCE_DECREMENT INITIAL_JUMP_FORCE / 10.0f
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
