#pragma once

// Screen
#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 896
#define SHAKE_DURATION 0.25f

// Map
#define MAP_WIDTH 32
#define MAP_HEIGHT 28

// Tiles
#define TILE_WIDTH (SCREEN_WIDTH / MAP_WIDTH)
#define TILE_HEIGHT (SCREEN_HEIGHT / MAP_HEIGHT)

// General Character Physics
#define GRAVITY_STRENGTH 260.0f
#define INITIAL_JUMP_FORCE 600.0f
#define JUMP_FORCE_DECREMENT 400.0f
#define INITIAL_BUMP_TIME 0.5f

// Player
#define PLAYER_WIDTH (TILE_WIDTH * 2)
#define PLAYER_HEIGHT (TILE_HEIGHT * 2.5)

#define PLAYER_SPRITE_WIDTH 16
#define PLAYER_SPRITE_HEIGHT 22

#define PLAYER_FRAME_DELAY 0.05f

#define PLAYER_SPEED 200.0f
#define PLAYER_JUMP_FORCE 700.0f

// Level 
#define INITIAL_ENEMY_WAVE_TIME 10.0f

// Enemy
#define INJURED_TIME 4.0f
#define ENEMY_JUMP_FORCE 600.0f

// Koopa
#define KOOPA_WIDTH 64
#define KOOPA_HEIGHT 64

#define KOOPA_SPRITE_WIDTH 16
#define KOOPA_SPRITE_HEIGHT 16

#define KOOPA_FRAME_DELAY 0.1f

#define KOOPA_SPEED 96.0f

#define KOOPA_SCORE_VALUE 1000

// Fly
#define FLY_WIDTH 48
#define FLY_HEIGHT 48

#define FLY_SPRITE_WIDTH 16
#define FLY_SPRITE_HEIGHT 16

#define FLY_FRAME_DELAY 0.2f

#define FLY_SPEED 80.0f
#define FLY_JUMP_FORCE 450.0f
#define FLY_JUMP_DELAY 1.0f

#define FLY_SCORE_VALUE 1200

// Coin
#define COIN_WIDTH 32
#define COIN_HEIGHT 44

#define COIN_SPRITE_WIDTH 16
#define COIN_SPRITE_HEIGHT 22
#define COIN_FRAME_DELAY 0.2f

#define COIN_POINT_VALUE 800